In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
print("Success")

Success

In [2]:
df = pd.read_csv('fods_1.csv')
df

     MLOGP  RDCHI  quantitative response of LC50
0    2.419  1.225                          3.740
1    2.638  1.401                          4.330
2    5.799  2.930                          7.019
3    5.453  2.887                          6.723
4    4.068  2.758                          5.979
..     ...    ...                            ...
541  3.326  2.837                          4.651
542  3.275  2.727                          3.953
543  5.165  3.111                          6.219
544  2.859  2.614                          4.995
545  2.255  1.800                          2.480

[546 rows x 3 columns]

In [4]:
meanX1 = df['MLOGP'].mean()
meanX2 = df['RDCHI'].mean()
meanY = df['quantitative response of LC50'].mean()
stdX1 = df['MLOGP'].std()
stdX2 = df['RDCHI'].std()
stdY = df['quantitative response of LC50'].std()
maxAll = df.max()
minAll = df.min()
print(meanX1, meanX2, meanY, stdX1, stdX2, stdY, maxAll, " ", minAll, sep = '\n')

2.3134926739926738
2.4922985347985356
4.6584212454212475
1.741797285664983
0.8110039291512505
1.6652150617992907
MLOGP                             9.148
RDCHI                             6.439
quantitative response of LC50    10.047
dtype: float64

MLOGP                           -6.446
RDCHI                            1.000
quantitative response of LC50    0.122
dtype: float64

In [5]:
df = (df-df.min())/(df.max()-df.min())
print(df.max(), df.min(), sep = '\n')
df

MLOGP                            1.0
RDCHI                            1.0
quantitative response of LC50    1.0
dtype: float64
MLOGP                            0.0
RDCHI                            0.0
quantitative response of LC50    0.0
dtype: float64

        MLOGP     RDCHI  quantitative response of LC50
0    0.568488  0.041368                       0.364534
1    0.582532  0.073727                       0.423980
2    0.785238  0.354845                       0.694912
3    0.763050  0.346939                       0.665088
4    0.674234  0.323221                       0.590126
..        ...       ...                            ...
541  0.626651  0.337746                       0.456322
542  0.623381  0.317522                       0.385995
543  0.744581  0.388123                       0.614307
544  0.596704  0.296746                       0.490982
545  0.557971  0.147086                       0.237582

[546 rows x 3 columns]

In [6]:
train, test = train_test_split(df, test_size=0.2) # this is a random split
train

        MLOGP     RDCHI  quantitative response of LC50
95   0.451199  0.161611                       0.273652
39   0.664807  0.274683                       0.628514
178  0.493267  0.194153                       0.549018
196  0.619213  0.169884                       0.484736
28   0.620495  0.299687                       0.426499
..        ...       ...                            ...
89   0.460434  0.284611                       0.315164
204  0.557073  0.203714                       0.394761
325  0.504104  0.197463                       0.491587
160  0.541939  0.269903                       0.367557
287  0.695267  0.467365                       0.449068

[436 rows x 3 columns]

In [7]:
test

        MLOGP     RDCHI  quantitative response of LC50
295  0.604527  0.328001                       0.640101
224  0.683596  0.310167                       0.613401
362  0.549570  0.451370                       0.421461
360  0.472682  0.400441                       0.380856
53   0.586636  0.298952                       0.592242
..        ...       ...                            ...
219  0.556111  0.048722                       0.354761
416  0.631076  0.311087                       0.535113
184  0.493267  0.189557                       0.391839
220  0.529883  0.041368                       0.315567
489  0.590227  0.341239                       0.369975

[110 rows x 3 columns]